kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: specfem-api
subjects:
- kind: ServiceAccount
  name: specfem-api
roleRef:
  kind: Role
  name: specfem-api
  apiGroup: rbac.authorization.k8s.io
